API Updates - #1
bootcamp-brian/Puppy_Paradise_Backend pull request #4
Opened 2023-02-24 20:11 UTC by bootcamp-brian

- Edited package.json so that we don't have the extra front end stuff in it (used fitnesstrackr backend as template)
- Created files for expected API routers
- Initial setup for index.js
- Initial drafts of most usersRouter functions
- Made a couple util functions for verification
- Moved a function I was working on in users to a separate admin.js file where I plan to create an adminRouter to next admin API functionality under (still needs to be added to index.js and need to change instances of userRouter to adminRouter in the file)

2023-02-26 03:53 UTC, this-journey requested changes
All the calls look good, I like the buildout for isAdmin.  Just a couple minor changes.

2023-02-26 03:53 UTC, this-journey commented on api/users.js
> +const { createUser, getUser, getOrderItemsByUser, updateUser } = require('../db');
getOrderItemsByUser is now called getOrderByUser per the changes

2023-02-26 03:53 UTC, this-journey commented on api/users.js
> +                })
Needs a different error message.

2023-02-26 03:53 UTC, this-journey commented on package.json
> +  "description": "an API for our new fitness empire, FitnessTrac.kr, using node, express, postgresql, and jQuery",
Change description

2023-02-27 20:34 UTC, bootcamp-brian commented on api/users.js
> +                })
Good catch, ty.

2023-02-27 20:34 UTC, bootcamp-brian commented on package.json
> +  "description": "an API for our new fitness empire, FitnessTrac.kr, using node, express, postgresql, and jQuery",
Good catch, ty.

2023-02-27 20:35 UTC, bootcamp-brian commented on api/users.js
> +const { createUser, getUser, getOrderItemsByUser, updateUser } = require('../db');
Will make the adjustment per changes.

2023-03-04 02:31 UTC, merged